{
 "title": "ZFS Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(zfs_pool_allocated, host)"
   },
   {
    "name": "list_of_pools",
    "label": "Pools",
    "query": "label_values(zfs_pool_allocated, pool)"
   }
  ]
 },
 "panels": [
  { "title": "ZFS Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "list_of_pools" },
  {
   "title": "ZFS Pools: size and capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "gbytes", "label": "GiB" }
   ],
   "targets": [
    {
     "expr": "zfs_pool_size{host=\"$host\", pool=\"$list_of_pools\"}/1024/1024/1024",
     "legendFormat": "{{pool}} size"
    },
    {
     "expr": "zfs_pool_allocated{host=\"$host\", pool=\"$list_of_pools\"}/1024/1024/1024",
     "legendFormat": "{{pool}}  allocated"
    },
    {
     "expr": "zfs_pool_free{host=\"$host\", pool=\"$list_of_pools\"}/1024/1024/1024",
     "legendFormat": "{{pool}} free "
    }
   ]
  },
  {
   "title": "Fragmentation & capacity usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "zfs_pool_fragmentation{host=\"$host\", pool=\"$list_of_pools\"}",
     "legendFormat": "{{pool}} fragmentation"
    },
    {
     "expr": "zfs_pool_capacity{host=\"$host\", pool=\"$list_of_pools\"}",
     "legendFormat": "{{pool}} capacity usage"
    }
   ]
  },
  {
   "title": "Pool status",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "zfs_pool_dedupratio{host=\"$host\", pool=\"$list_of_pools\"}",
     "legendFormat": "{{health}}"
    }
   ]
  },
  { "title": "Pool throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Read/write MBs per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "irate(zfs_pool_nread{host=\"$host\"}[1m])/1024/1024",
     "legendFormat": "{{pool}} read"
    },
    {
     "expr": "irate(zfs_pool_nwritten{host=\"$host\"}[1m])/1024/1024",
     "legendFormat": "{{pool}} write "
    }
   ]
  },
  {
   "title": "Read/write operations per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(zfs_pool_reads{host=\"$host\"}[1m])",
     "legendFormat": "{{pool}} read"
    },
    {
     "expr": "irate(zfs_pool_writes{host=\"$host\"}[1m])",
     "legendFormat": "{{pool}} write"
    }
   ]
  },
  { "title": "Pool latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Cumulative run (service) and wait(pre-served) time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(zfs_pool_rtime{host=\"$host\"}[1m])/1000000",
     "legendFormat": "{{pool}}  run time"
    },
    {
     "expr": "irate(zfs_pool_wtime{host=\"$host\"}[1m])/1000000",
     "legendFormat": "{{pool}} wait  time"
    }
   ]
  },
  {
   "title": "Cumulative run/wait queues length * time product",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(zfs_pool_rlentime{host=\"$host\"}[1m])/1000000",
     "legendFormat": "{{pool}}  run length*time "
    },
    {
     "expr": "irate(zfs_pool_wlentime{host=\"$host\"}[1m])/1000000",
     "legendFormat": "{{pool}} wait length*time "
    }
   ]
  },
  { "title": "Pool run/wait queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Pool run/wait queue length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zfs_pool_rcnt{host=\"$host\"}",
     "legendFormat": "{{pool}} run queue length"
    },
    {
     "expr": "zfs_pool_wcnt{host=\"$host\"}",
     "legendFormat": "{{pool}} wait queue length"
    }
   ]
  },
  {
   "title": "Average run/wait queue length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(zfs_pool_rlentime{host=\"$host\"}[1m])/increase(zfs_pool_rtime{host=\"$host\"}[1m])",
     "legendFormat": "{{pool}}  average run queue length"
    },
    {
     "expr": "increase(zfs_pool_wlentime{host=\"$host\"}[1m])/increase(zfs_pool_wtime{host=\"$host\"}[1m])",
     "legendFormat": "{{pool}} average run queue length"
    }
   ]
  }
 ]
}